[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "fastapi[standard]>=0.122.0",
  "sqlmodel>=0.0.27",
  "uvicorn>=0.38.0",
  "passlib[bcrypt]>=1.7.4",
  "bcrypt<4",
  "python-jose[cryptography]>=3.5.0"
]
